### ISSUE TITLE
Add Bitcointoyou brazilian exchange

### ISSUE THREAD

**Issue by andrehortab2u** [dashpay/docs#13]
Dears

Could you please include Bitcointoyou.com exchange? It is the pioneer cryptocurrency exchange in Brazil, with more than 300 thousand customers, founded in 2010. We love Dash!

**Comment by strophy** [comment]
Added, thanks for reaching out!
https://github.com/dashpay/docs/commit/2c4f25e7f7703eee7dd0b2fee2dba75105404e92
