### ISSUE TITLE
Another point worth mentioning here is that if both `sendheaders` and `sendheaders2` are sent by a peer, the peer will receive block announcements via compressed headers (even though `sendheaders` was sent after `sendheaders2`).

### ISSUE THREAD

**Issue by Donabbaskid** [dashpay/docs#141]
Another point worth mentioning here is that if both `sendheaders` and `sendheaders2` are sent by a peer, the peer will receive block announcements via compressed headers (even though `sendheaders` was sent after `sendheaders2`).

_Originally posted by @gabriel-bjg in https://github.com/dashpay/dips/pull/113#discussion_r897590582_

**Comment by thephez** [comment]
Closing since this repo doesn't really discuss the p2p messages at that level of detail
