### ISSUE TITLE
must restart MN after changing mastenodeblsprivkey

### ISSUE THREAD

**Issue by taw00** [dashpay/docs#20]
in masternodes/setup.rst (and masternodes/maintenance.rst), you discuss adding this to dash.conf on the masternode:
`masternodeblsprivkey=565950700d7bdc6a9dbc9963920bc756551b02de6e4711eff9ba6d4af59c0101`

After altering any setting in dash.conf, you have to reboot the node in order for that to be recognized by the masternode. Unless in 0.13.0 the dash.conf update behavior is suddenly more dynamic than it was which I do not think is the case. The need to bounce the masternode is not mentioned. Or at least, I didn't see it.

Thanks -t0dd

**Comment by strophy** [comment]
You're absolutely right - good catch. Docs have been updated.
