### ISSUE TITLE
Cleanup dead wallets from Third Party Wallets list

### ISSUE THREAD

**Issue by mahnunchik** [dashpay/docs#214]
While I was adding a new wallet, I noticed that there are a lot of dead wallets. I think they may be removed from the list to not confuse users.

If you wish I may prepare a PR.

## Cryptonator

https://docs.dash.org/en/stable/docs/user/wallets/third-party.html#cryptonator

It seems it is down from 2021 https://twitter.com/cryptonatorcom

Website is down and app is unavailable https://play.google.com/store/apps/details?id=com.cryptonator.android

## Evercoin

https://evercoin.com/

Website is down, iOS app is unavailable.

## KurePay

https://docs.dash.org/en/stable/docs/user/wallets/third-party.html#kurepay

Domain is for sale. App is unavailable https://play.google.com/store/apps/details?id=com.kurewallet

## Magnum

https://docs.dash.org/en/stable/docs/user/wallets/third-party.html#magnum

Website is down, app is still present but not available for installation.

## Paytomat

https://docs.dash.org/en/stable/docs/user/wallets/third-party.html#paytomat

Website is down, Android and iOS apps are unavailable.

No any update since 2020 https://twitter.com/paytomat

## Spend

https://docs.dash.org/en/stable/docs/user/wallets/third-party.html#spend

Closed in 2022 according to the information on the website.

**Comment by thephez** [comment]
Thanks!
