### ISSUE TITLE
Broken link to bitcore

### ISSUE THREAD

**Issue by bappelt** [dashpay/docs#82]
There is a broken link in this section 

https://github.com/dashpay/docs/blob/0.16.0/developers/integration.rst#nodejsjavascript-dashcore

link is: `Documentation: https://bitcore.io/api/lib`

**Comment by thephez** [comment]
@strophy Any idea what this should be linked to? bitcore.io now just redirects to a GH readme.

**Comment by strophy** [comment]
I'm not sure either, is `dashcore-lib` even still a fork of this version of bitcore?I would say we can just link to the `docs` in the repo itself, they seem to be fairly detailed already.
